version: '3'

services:
  javalee:
    container_name: javalee
    build:
      context: .
    volumes:
      - '.:/app/javalee'
    ports:
      - "8089:8080"
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306'
volumes:
  mysql_data:
